<a href="https://colab.research.google.com/github/ThOliveira23/PH482_582_Sp22/blob/main/Exercises/00_Exercise0_Thales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 0
Due date: 2022-01-25

This is the zeroth exercise just to review python and show you how to submit exercises.

File name convention: For group 42 and memebers Richard Stallman and Linus Torvalds it would be 
"00_Exercise0_Goup42_Stallman_Torvalds.pdf".
Just give yourself a funny group name for this exercise!

Submission via blackboard everyone individually (for this exercise).

In [1]:
group_name = "insert group name"
group_members = ["name 1", 
         "name 2", 
         "name 3"]

<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/UAPH4582/PH482_582_Sp22/blob/main/Exercises/00_PythonPrimer.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
</table>

## Functions

### Task 1
Write a function `subtract` that takes two numbers `a` and `b` and returns `a-b`.

In [2]:
# your code goes below
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

In [3]:
def subtract(a,b):
  return a-b

In [4]:
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# your code goes above this

In [5]:
# testing if the function is working
subtract(3, 5) == -2

True

### Task 2
a) Write a function `fac_it` that calculates the factorial in an iterative way.   
b) (optional) Write a function `fac_rec` that computes the factorial in a recursive way.

**Hints**    
a) Set a variable `fac = 1`, loop over `i in range(2,n+1)` and in the loop muliply `fac` by `i`.   
b) The trick is to set the cases for `n=0` and `n=1` and then call something like `n*fac_rec(n-1)`.   

In [9]:
# your code goes below
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

In [6]:
def fac_it(n):
  if n == 0:
    return 1
  elif n == 1:
    return 1
  else:
    fac = 1 
    for i in range(2,n+1):
      fac = fac*i
    return fac

In [7]:
fac_it(4)

24

In [8]:
def fac_rec(n):
  if n == 0:
    return 1
  elif n == 1:
    return 1
  else:
    return n*fac_rec(n-1)

In [15]:
print(fac_rec(3) == 6)
print(fac_it(3) == 6)

True
True


In [16]:
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# your code goes above this

## Numpy

In [9]:
import numpy as np

You can read about this dataset [here](https://inria.github.io/scikit-learn-mooc/python_scripts/datasets_california_housing.html).
`X` are some features of houses and `y` is the price of the houses in 100k$.

In [10]:
from sklearn.datasets import fetch_california_housing

california_housing = fetch_california_housing()

In [11]:
california_housing.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [12]:
X = california_housing['data']
y = california_housing['target']

In [42]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [13]:
print(y)

[4.526 3.585 3.521 ... 0.923 0.847 0.894]


### Task 3
1) Find out how many instances there are in `X` and `y`. You can use `.shape` or `len`.

In [ ]:
# your code goes below
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

In [38]:
"Data:", X.shape

('Data:', (20640, 8))

In [39]:
"Target:", y.shape

('Target:', (20640,))

In [ ]:
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# your code goes above this

2) Make a mask `y_200k_mask` that is `True` whenever the house costs more than or exactly 200k$ and `False` if it costs less.

In [ ]:
# your code goes below
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

In [56]:
y_200k_mask = y[y >= 2]

In [57]:
y_200k_mask

array([4.526, 3.585, 3.521, ..., 2.007, 2.25 , 2.75 ])

In [ ]:
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# your code goes above this

3) Use [`Counter`](https://docs.python.org/3/library/collections.html#collections.Counter) to find out how many houses are woth more than 200k$.

In [ ]:
from collections import Counter

In [ ]:
# your code goes below
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

In [ ]:
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# your code goes above this

By calling `arr[mask]` you can extract only those items from a numpy array where `mask` is `True`.    
4) Put all `X` where the price is in `X_200k` and the corresponding `y` in `y_200k`.

In [ ]:
# your code goes below
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

In [ ]:

# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# your code goes above this

## Pandas Dataframes

In [ ]:
from sklearn.datasets import fetch_california_housing

california_housing_df = fetch_california_housing(as_frame=True)

In [ ]:
X_df = california_housing_df['data']
y_df = california_housing_df['target']

### Task 4
1) Get a [description](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html) of the `X_df` and `y_df`.   

In [ ]:
# your code goes below
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

In [ ]:
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# your code goes above this

2) Get all elements of the dataframe where the price is >= 200k$. You don't have to convert anything to numpy arrays.

In [ ]:
# your code goes below
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

In [ ]:
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# your code goes above this

3) Plot the [histogram](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.hist.html) of `X_df` and `y_df`.

In [ ]:
# your code goes below
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

In [ ]:
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# your code goes above this

# Solutions

In [ ]:
def fac_rec(n):
  if n == 0:
    return 1
  elif n == 1:
    return 1
  else:
    return n*fac_rec(n-1)